/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DogeBetsPrediction__factory } from "./DogeBetsPrediction__factory";
export { PancakePrediction__factory } from "./PancakePrediction__factory";
