/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DogeBetsPrediction } from "./DogeBetsPrediction";
export type { PancakePrediction } from "./PancakePrediction";
export * as factories from "./factories";
export { DogeBetsPrediction__factory } from "./factories/DogeBetsPrediction__factory";
export { PancakePrediction__factory } from "./factories/PancakePrediction__factory";
